=== diogoalves10/PRI/TPC2/PR.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT PR (CABEÇALHO,WORKTEAM,ABSTRACT,DELIVERABLES+) >
<!ELEMENT CABEÇALHO (KEYNAME,TITLE,SUBTITLE,BEGINDATE, ENDDATE, SUPERVISOR) >
<!ELEMENT KEYNAME EMPTY >
<!ELEMENT TITLE EMPTY >
<!ELEMENT SUBTITLE EMPTY >
<!ELEMENT BEGINDATE EMPTY >
<!ELEMENT ENDDATE EMPTY >
<!ELEMENT SUPERVISOR (#PCDATA) >
<!ELEMENT WORKTEAM (ELEMENTO)+ >
<!ELEMENT ELEMENTO EMPTY >
<!ELEMENT ABSTRACT (#PCDATA) >
<!ELEMENT DELIVERABLES (#PCDATA) >



<!ATTLIST KEYNAME
    KEYNAME CDATA #REQUIRED 
>
<!ATTLIST TITLE 
    TITLE CDATA #REQUIRED 
    >

<!ATTLIST TITLE 
   SUBTITLE CDATA #IMPLIED
    
>
    
<!ATTLIST BEGINDATE
   BEGINDATE CDATA #REQUIRED
    
>

<!ATTLIST ENDDATE
  ENDDATE CDATA #REQUIRED
    
    >
     
    
<!ATTLIST SUPERVISOR
  SUPERVISOR CDATA #REQUIRED
    
>
     
    
<!ATTLIST ELEMENTO 
    id CDATA #REQUIRED 
    NOME CDATA #REQUIRED 
    NUMERO CDATA #REQUIRED
    EMAIL CDATA #REQUIRED
>

=== diogoalves10/PRI/TPC2/TP2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE PR SYSTEM "pr.dtd">
<PR>
    <CABEÇALHO>
        <KEYNAME KEYNAME=""/>
        <TITLE TITLE=""/>
        <SUBTITLE/>
        <BEGINDATE BEGINDATE=""/>
        <ENDDATE ENDDATE=""/>
        <SUPERVISOR SUPERVISOR=""></SUPERVISOR>
    </CABEÇALHO>
    <WORKTEAM>
        <ELEMENTO id="" NOME="" NUMERO="" EMAIL=""/>
    </WORKTEAM>
    <ABSTRACT></ABSTRACT>
    <DELIVERABLES></DELIVERABLES>
</PR>
